import { GetStaticProps } from "next";
import Head from "next/head";
import ProjectCard from "../../components/ProjectCard";
import fetchData from "../../lib/fetchData";
import Center from "../../components/Center";
import Grid from "../../components/Grid";
import Link from "next/link";
import Nav from "../../components/Nav";

export default function AllProjectsPage({ projects }: { projects: Project[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Center maxWidth="1024px">
        <Nav lang="he" />
        <header>
          <h1>{}</h1>
        </header>
        <main style={{ width: "100%" }}>
          <Grid>
            {projects.map((project) => (
              <Link href={`/projects/${project.id}`} key={project.id}>
                <a
                  style={{
                    textDecoration: "none",
                    color: "unset",
                  }}
                >
                  <article>
                    <ProjectCard project={project} />
                  </article>
                </a>
              </Link>
            ))}
          </Grid>
        </main>
      </Center>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const projects = await fetchData();
  return {
    props: {
      projects,
    },
  };
};
