import { GetStaticProps } from "next";
import Head from "next/head";
import fetchData from "../lib/fetchData";
import Center from "../components/Center";
import Nav from "../components/Nav";

export default function Home({ projects }: { projects: Project[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center maxWidth="1024px">
        <Nav lang="he" />
        <header>
          <h1></h1>
        </header>
      </Center>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const projects = await fetchData();
  return {
    props: {
      projects,
    },
  };
};
